// Checks the Frisch chocolate model against independent calculations.
// Run with:  node frisch-chocolate/test-model.cjs
const assert = require('node:assert/strict');
const M = require('./model.js');

const close = (a, b, tol = 1e-9, msg = '') =>
  assert.ok(Math.abs(a - b) <= tol * Math.max(1, Math.abs(b)), `${msg} ${a} != ${b}`);
let checks = 0;
const { DATA } = M;

// 1. The table as printed in the notes (Frisch 1935, Table 5a.8); the cells circled in the notes.
assert.deepEqual(DATA.q[0], [352, 396, 402, 403]);
assert.deepEqual(DATA.q[3], [738, 858, 930, 957]);
assert.equal(M.value(1, 2), 577); // (150 kr, 15 kr)
assert.equal(M.value(3, 0), 738); // (250 kr, 5 kr)
checks += 4;

// 2. Interpolation returns the data at the nodes, is linear along grid lines, NaN outside.
for (let i = 0; i < 4; i++) for (let j = 0; j < 4; j++) { close(M.interpolate(DATA.z1[i], DATA.z2[j]), M.value(i, j)); checks++; }
close(M.interpolate(125, 5), (352 + 500) / 2);
close(M.interpolate(100, 12.5), (396 + 402) / 2);
close(M.interpolate(125, 7.5), (352 + 500 + 396 + 562) / 4);
assert.ok(Number.isNaN(M.interpolate(90, 10)) && Number.isNaN(M.interpolate(150, 25)));
checks += 4;

// 3. Marginal products are difference quotients, worked out by hand for cell (150 kr, 10 kr).
{
  const { mp1, mp2 } = M.marginalProducts(1, 1);
  close(mp1.back, (562 - 396) / 50); close(mp1.fwd, (725 - 562) / 50); close(mp1.est, (725 - 396) / 100);
  close(mp2.back, (562 - 500) / 5); close(mp2.fwd, (577 - 562) / 5); close(mp2.est, (577 - 500) / 10);
  close(M.mrts(1, 1), ((725 - 396) / 100) / ((577 - 500) / 10));
  // Corners have only one side.
  const c = M.marginalProducts(0, 3);
  assert.equal(c.mp1.back, null); assert.equal(c.mp2.fwd, null);
  close(c.mp1.est, (589 - 403) / 50); close(c.mp2.est, (403 - 402) / 5);
  checks += 11;
}

// 4. Cocoa fat has diminishing marginal product in every row of the table.
for (let i = 0; i < 4; i++) {
  for (let j = 1; j + 1 < 4; j++) {
    const { mp2 } = M.marginalProducts(i, j);
    assert.ok(mp2.fwd < mp2.back, `row ${i}`);
    checks++;
  }
}

// 5. Cells on a common ray: found by brute force over all pairs; arc elasticities by hand.
{
  const pairs = M.scalePairs();
  let count = 0;
  for (const a of DATA.z1) for (const b of DATA.z2) for (const c of DATA.z1) for (const d of DATA.z2) {
    if (c > a && Math.abs(c / a - d / b) < 1e-12) count++;
  }
  assert.equal(pairs.length, count);
  assert.equal(count, 4);
  const find = (i, j) => pairs.find(p => p.from[0] === i && p.from[1] === j && p.lambda === 2);
  close(find(0, 0).e, Math.log(725 / 352) / Math.log(2));
  close(find(0, 1).e, Math.log(783 / 396) / Math.log(2));
  for (const p of pairs) assert.ok(p.e > 0.9 && p.e < 1.1); // close to constant returns
  checks += 2 + pairs.length + 2;
}

// 6. The Cobb-Douglas fit: exact on data generated by a Cobb-Douglas function ...
{
  const truth = { A: 3.2, alpha: 0.7, beta: 0.25 }, cells = [];
  for (const a of DATA.z1) for (const b of DATA.z2) cells.push([a, b, M.cdOutput(a, b, truth)]);
  const f = M.fitCobbDouglas(cells);
  close(f.A, truth.A, 1e-9); close(f.alpha, truth.alpha, 1e-9); close(f.beta, truth.beta, 1e-9); close(f.r2, 1, 1e-12);
  checks += 4;
}
// ... and on Frisch's data the residuals are orthogonal to the regressors (OLS normal equations).
{
  const f = M.fitCobbDouglas(), sums = [0, 0, 0];
  for (let i = 0; i < 4; i++) for (let j = 0; j < 4; j++) {
    const r = Math.log(M.value(i, j)) - Math.log(M.cdOutput(DATA.z1[i], DATA.z2[j], f));
    sums[0] += r; sums[1] += r * Math.log(DATA.z1[i]); sums[2] += r * Math.log(DATA.z2[j]);
  }
  sums.forEach(s => assert.ok(Math.abs(s) < 1e-9, `normal equation ${s}`));
  assert.ok(f.r2 > 0.98 && Math.abs(f.alpha + f.beta - 1) < 0.1);
  checks += 4;
}

// 7. The linear solver used for the fit.
{
  const x = M.solve([[2, 1, 0], [1, 3, 1], [0, 1, 4]], [3, 7, 13]);
  [1, 1, 3].forEach((v, k) => close(x[k], v, 1e-12));
  checks += 3;
}

console.log(`All ${checks} model checks passed.`);
