// node tools/build-site.cjs
// Writes index.html (one tile per tool, from tools/catalog.cjs and the drawings in tools/glyphs.cjs) and, on every
// tool page, the "Microvis /" link in the header and the "previous / next" links above the footer.
// Run it after adding a tool to the catalog or changing a tile; it can be run any number of times.
const fs = require('fs');
const path = require('path');
const catalog = require('./catalog.cjs');
const glyphs = require('./glyphs.cjs');

const ROOT = path.join(__dirname, '..');
const V = (fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8').match(/style\.css\?v=(\d+)/) || [, '1'])[1];
const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Visitor counts (GoatCounter, dashboard at https://microvis.goatcounter.com): one request per page view, only on the
// published site (not on previews or local copies), no cookies, no external script. On the start page it also shows the
// site total in the footer (needs "Allow adding visitor counts on your website" in the GoatCounter settings; the total
// is cached there for up to four hours). If GoatCounter cannot be reached, nothing is shown and nothing else is affected.
const COUNTER = `<script>/* visitor count */if(location.hostname==='lukaslaffers.github.io'){new Image().src='https://microvis.goatcounter.com/count?p='+encodeURIComponent(location.pathname.replace(/index\\.html$/,''))+'&t='+encodeURIComponent(document.title)+'&r='+encodeURIComponent(document.referrer)+'&rnd='+Math.random().toString(36).slice(2);var v=document.getElementById('visits');if(v&&window.fetch)fetch('https://microvis.goatcounter.com/counter/TOTAL.json').then(function(r){return r.ok?r.json():null}).then(function(d){if(d&&d.count){v.textContent=' · '+d.count+' visits';v.hidden=false}}).catch(function(){});}</script>`;
const withCounter = html => html.replace(/\n? *<script>\/\* visitor count \*\/[^\n]*<\/script>/, '').replace(/\n<\/body>/, '\n  ' + COUNTER + '\n</body>');

// Light / dark switch (shared/theme.js): a remembered choice is applied in <head> before the page is drawn, the button
// sits in the top right corner of the header, and the script is loaded at the end of <body>.
const THEME_HEAD = `<script>/* theme */try{var t=localStorage.getItem('microvis-theme');if(t==='dark'||t==='light')document.documentElement.dataset.theme=t}catch(e){}</script>`;
const THEME_BUTTON = '<button class="theme-toggle" type="button" aria-label="Switch to dark mode" aria-pressed="false">' +
  '<svg class="moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M20 14.5A8 8 0 0 1 9.5 4a8 8 0 1 0 10.5 10.5z"/></svg>' +
  '<svg class="sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="4.2"/><path d="M12 2.5v2.3M12 19.2v2.3M2.5 12h2.3M19.2 12h2.3M5.3 5.3l1.6 1.6M17.1 17.1l1.6 1.6M5.3 18.7l1.6-1.6M17.1 6.9l1.6-1.6"/></svg></button>';
const withTheme = (html, prefix) => html
  .replace(/\n? *<script>\/\* theme \*\/[^\n]*<\/script>/, '')
  .replace(/\n? *<button class="theme-toggle"[^\n]*<\/button>/, '')
  .replace(/\n? *<script src="[^"]*shared\/theme\.js[^"]*"><\/script>/, '')
  .replace(/\n<\/head>/, '\n  ' + THEME_HEAD + '\n</head>')
  .replace(/(<header class="site-header">)/, '$1\n    ' + THEME_BUTTON)
  .replace(/\n<\/body>/, `\n  <script src="${prefix}shared/theme.js?v=${V}"></script>\n</body>`);

const order = [];
for (const sec of catalog) for (const [slug, title, blurb, star] of sec.tools) order.push({ slug, title, blurb, star, sec });

const card = t => {
  if (!glyphs[t.slug]) throw new Error('no drawing for ' + t.slug);
  const prev = fs.existsSync(path.join(ROOT, t.slug, 'preview.webp'))
    ? `\n        <picture class="preview" aria-hidden="true" style="display:none"><source srcset="${t.slug}/preview-dark.webp" media="(prefers-color-scheme: dark)"><img src="${t.slug}/preview.webp" alt="" loading="lazy" decoding="async"></picture>` : '';
  return `      <a class="card" href="${t.slug}/index.html">
        ${glyphs[t.slug]}${prev}
        <h3>${t.star ? '<span class="star">*</span>' : ''}${esc(t.title)}</h3>
        <p>${esc(t.blurb)}</p>
      </a>`;
};

const index = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Microvis — Visualizations for Microeconomic theory</title>
  <meta name="description" content="Interactive figures for microeconomic theory: production, costs, markets, consumer demand, welfare and general equilibrium.">
  <link rel="icon" href="data:,">
  <link rel="stylesheet" href="shared/style.css?v=${V}">
</head>
<body class="home">
  <!-- Generated by tools/build-site.cjs from tools/catalog.cjs: edit those, not this file. -->
  <header class="site-header">
    <div>
      <h1>Microvis</h1>
      <p class="lead">Interactive figures for microeconomic theory.</p>
    </div>
  </header>

  <main>
    <p class="wip" role="note"><b>Work in progress.</b> The tools are still being developed and checked. Feedback of any kind is very welcome: errors, unclear explanations, ideas for new tools.</p>
    <nav class="lecture-nav" aria-label="Lectures">
${catalog.map(s => `      <a href="#${s.id}"><b>${s.lecture}</b> ${esc(s.nav)}</a>`).join('\n')}
    </nav>
${catalog.map(s => `
    <section class="lecture" id="${s.id}" aria-labelledby="${s.id}-title">
      <h2 class="lecture-title" id="${s.id}-title"><span class="lecture-no">Lecture ${s.lecture}</span> ${esc(s.title)}</h2>
      <div class="cards">
${s.tools.map((_, i) => card(order.find(t => t.slug === s.tools[i][0]))).join('\n')}
      </div>
    </section>`).join('\n')}
  </main>

  <footer class="site-footer">
    Lukáš Lafférs<span id="visits" hidden></span>
  </footer>
</body>
</html>
`;
fs.writeFileSync(path.join(ROOT, 'index.html'), withCounter(withTheme(index, '')));

// Tool pages: header link and pager.
let changed = 0;
order.forEach((t, i) => {
  const file = path.join(ROOT, t.slug, 'index.html');
  let s = fs.readFileSync(file, 'utf8');
  const before = s;
  const home = `../index.html#${t.sec.id}`;
  s = s.replace(/<p class="eyebrow">(?:<a [^>]*>Microvis<\/a> <span class="sep"[^>]*>\/<\/span> )?([\s\S]*?)<\/p>/,
    (_, rest) => `<p class="eyebrow"><a href="${home}">Microvis</a> <span class="sep" aria-hidden="true">/</span> ${rest}</p>`);
  s = s.replace(/\n\s*<a class="back-link"[^>]*>[^<]*<\/a>/, '');
  const p = order[i - 1], n = order[i + 1];
  const link = (u, cls, label) => u ? `<a class="${cls}" href="../${u.slug}/index.html"><span>${label}</span>${esc(u.title)}</a>` : `<span class="${cls}"></span>`;
  const pager = `<nav class="pager" aria-label="Other tools">\n    ${link(p, 'prev', 'Previous')}\n    <a class="all" href="${home}">All tools</a>\n    ${link(n, 'next', 'Next')}\n  </nav>\n\n  `;
  s = s.replace(/<nav class="pager"[\s\S]*?<\/nav>\n\n {2}/, '');
  s = s.replace(/<footer class="site-footer">/, pager + '<footer class="site-footer">');
  s = withCounter(withTheme(s, '../'));
  if (s !== before) { fs.writeFileSync(file, s); changed++; }
});
console.log(`index.html: ${order.length} tiles; ${changed} tool pages updated`);
