// node tools/build-site.cjs
// Writes index.html (one tile per page, from tools/catalog.cjs and the drawings in tools/glyphs.cjs) and, on every
// page, the "Site /" link in the header and the "previous / next" links above the footer.
// Run it after adding a page to the catalog or changing a tile; it can be run any number of times.
const fs = require('fs');
const path = require('path');
const { site, sections } = require('./catalog.cjs');
const glyphs = require('./glyphs.cjs');

const ROOT = path.join(__dirname, '..');
const indexFile = path.join(ROOT, 'index.html');
const V = fs.existsSync(indexFile) ? (fs.readFileSync(indexFile, 'utf8').match(/style\.css\?v=(\d+)/) || [, '1'])[1] : '1';
const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Light / dark switch (shared/theme.js): a remembered choice is applied in <head> before the page is drawn, the button
// sits in the top right corner of the header, and the script is loaded at the end of <body>.
const THEME_HEAD = `<script>/* theme */try{var t=localStorage.getItem('microvis-theme');if(t==='dark'||t==='light')document.documentElement.dataset.theme=t}catch(e){}</script>`;
const THEME_BUTTON = '<button class="theme-toggle" type="button" aria-label="Switch to dark mode" aria-pressed="false">' +
  '<svg class="moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M20 14.5A8 8 0 0 1 9.5 4a8 8 0 1 0 10.5 10.5z"/></svg>' +
  '<svg class="sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="4.2"/><path d="M12 2.5v2.3M12 19.2v2.3M2.5 12h2.3M19.2 12h2.3M5.3 5.3l1.6 1.6M17.1 17.1l1.6 1.6M5.3 18.7l1.6-1.6M17.1 6.9l1.6-1.6"/></svg></button>';
const withTheme = (html, prefix) => html
  .replace(/\n? *<script>\/\* theme \*\/[^\n]*<\/script>/, '')
  .replace(/\n? *<button class="theme-toggle"[^\n]*<\/button>/, '')
  .replace(/\n? *<script src="[^"]*shared\/theme\.js[^"]*"><\/script>/, '')
  .replace(/\n<\/head>/, '\n  ' + THEME_HEAD + '\n</head>')
  .replace(/(<header class="site-header">)/, '$1\n    ' + THEME_BUTTON)
  .replace(/\n<\/body>/, `\n  <script src="${prefix}shared/theme.js?v=${V}"></script>\n</body>`);

const order = [];
for (const sec of sections) for (const [slug, title, blurb, star] of sec.pages) order.push({ slug, title, blurb, star, sec });

const card = t => {
  if (!glyphs[t.slug]) throw new Error('no drawing for ' + t.slug + ' in tools/glyphs.cjs');
  const prev = fs.existsSync(path.join(ROOT, t.slug, 'preview.webp'))
    ? `\n        <picture class="preview" aria-hidden="true" style="display:none"><source srcset="${t.slug}/preview-dark.webp" media="(prefers-color-scheme: dark)"><img src="${t.slug}/preview.webp" alt="" loading="lazy" decoding="async"></picture>` : '';
  return `      <a class="card" href="${t.slug}/index.html">
        ${glyphs[t.slug]}${prev}
        <h3>${t.star ? '<span class="star">*</span>' : ''}${esc(t.title)}</h3>
        <p>${esc(t.blurb)}</p>
      </a>`;
};

const index = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(site.pageTitle || site.title)}</title>
  <meta name="description" content="${esc(site.lead)}">
  <link rel="icon" href="data:,">
  <link rel="stylesheet" href="shared/style.css?v=${V}">
</head>
<body class="home">
  <!-- Generated by tools/build-site.cjs from tools/catalog.cjs: edit those, not this file. -->
  <header class="site-header">
    <div>
      <h1>${esc(site.title)}</h1>
      <p class="lead">${esc(site.lead)}</p>
    </div>
  </header>

  <main>
${site.note ? `    <p class="wip" role="note">${site.note}</p>\n` : ''}    <nav class="lecture-nav" aria-label="Sections">
${sections.map((s, i) => `      <a href="#${s.id}"><b>${i + 1}</b> ${esc(s.nav)}</a>`).join('\n')}
    </nav>
${sections.map(s => `
    <section class="lecture" id="${s.id}" aria-labelledby="${s.id}-title">
      <h2 class="lecture-title" id="${s.id}-title"><span class="lecture-no">${esc(s.label)}</span> ${esc(s.title)}</h2>
      <div class="cards">
${s.pages.map(p => card(order.find(t => t.slug === p[0]))).join('\n')}
      </div>
    </section>`).join('\n')}
  </main>

  <footer class="site-footer">
    ${site.footer || ''}
  </footer>
</body>
</html>
`;
fs.writeFileSync(indexFile, withTheme(index, ''));

// Pages: header link and pager.
let changed = 0;
order.forEach((t, i) => {
  const file = path.join(ROOT, t.slug, 'index.html');
  if (!fs.existsSync(file)) { console.warn('missing page ' + t.slug + '/index.html'); return; }
  let s = fs.readFileSync(file, 'utf8');
  const before = s;
  const home = `../index.html#${t.sec.id}`;
  const siteName = esc(site.title);
  s = s.replace(/<p class="eyebrow">(?:<a [^>]*>[^<]*<\/a> <span class="sep"[^>]*>\/<\/span> )?([\s\S]*?)<\/p>/,
    (_, rest) => `<p class="eyebrow"><a href="${home}">${siteName}</a> <span class="sep" aria-hidden="true">/</span> ${rest}</p>`);
  const p = order[i - 1], n = order[i + 1];
  const link = (u, cls, label) => u ? `<a class="${cls}" href="../${u.slug}/index.html"><span>${label}</span>${esc(u.title)}</a>` : `<span class="${cls}"></span>`;
  const pager = `<nav class="pager" aria-label="Other pages">\n    ${link(p, 'prev', 'Previous')}\n    <a class="all" href="${home}">All pages</a>\n    ${link(n, 'next', 'Next')}\n  </nav>\n\n  `;
  s = s.replace(/<nav class="pager"[\s\S]*?<\/nav>\n\n {2}/, '');
  s = s.replace(/<footer class="site-footer">/, pager + '<footer class="site-footer">');
  s = withTheme(s, '../');
  if (s !== before) { fs.writeFileSync(file, s); changed++; }
});
console.log(`index.html: ${order.length} tiles; ${changed} pages updated`);
